export interface FieldSchema { name: string; type: string; description: string }

export const NODE_OUTPUT_SCHEMAS: Record<string, FieldSchema[]> = {
  manualTrigger: [{ name: 'trigger', type: 'string', description: '"manual"' }],
  scheduleTrigger: [
    { name: 'trigger', type: 'string', description: '"schedule"' },
    { name: 'triggered_at', type: 'string', description: 'ISO 时间' },
    { name: 'timestamp', type: 'number', description: 'Unix 时间戳' },
    { name: 'date', type: 'string', description: 'YYYY-MM-DD' },
    { name: 'time', type: 'string', description: 'HH:MM:SS' },
  ],
  webhookTrigger: [
    { name: 'trigger', type: 'string', description: '"webhook"' },
    { name: 'body', type: 'object', description: '请求体 JSON' },
  ],
  ai: [
    { name: 'text', type: 'string', description: 'AI 生成文本' },
    { name: 'ai_result', type: 'string', description: '同 text' },
    { name: 'category', type: 'string', description: '分类结果 (classify)' },
    { name: 'extracted', type: 'object', description: '结构化数据 (extract)' },
    { name: 'summary', type: 'string', description: '摘要 (summarize)' },
    { name: 'route', type: 'string', description: '路由名 (route)' },
  ],
  http: [
    { name: 'status_code', type: 'number', description: 'HTTP 状态码' },
    { name: 'data', type: 'any', description: '响应数据' },
    { name: 'ok', type: 'boolean', description: '是否 2xx' },
  ],
  code: [{ name: 'result', type: 'any', description: 'result 变量的值' }],
  condition: [{ name: 'condition_result', type: 'boolean', description: '条件结果' }],
  if: [{ name: 'condition_result', type: 'boolean', description: '条件结果' }],
  switch: [{ name: 'matched_route', type: 'number', description: '匹配索引' }, { name: 'matched_value', type: 'string', description: '匹配值' }],
  set: [{ name: '(自定义)', type: 'any', description: '按 assignments 输出' }],
  excel: [
    { name: 'items', type: 'array', description: '数据行 (read)' },
    { name: 'headers', type: 'array', description: '表头' },
    { name: 'row_count', type: 'number', description: '行数' },
    { name: 'path', type: 'string', description: '文件路径 (create)' },
  ],
  email: [{ name: 'status', type: 'string', description: '"sent"/"draft"' }, { name: 'to', type: 'string', description: '收件人' }],
  notification: [{ name: 'notification_sent', type: 'boolean', description: '是否成功' }, { name: 'title', type: 'string', description: '标题' }],
  feishu: [{ name: 'sent', type: 'boolean', description: '是否成功' }, { name: 'status_code', type: 'number', description: 'HTTP 码' }],
  dingtalk: [{ name: 'sent', type: 'boolean', description: '是否成功' }, { name: 'status_code', type: 'number', description: 'HTTP 码' }],
  wecom: [{ name: 'sent', type: 'boolean', description: '是否成功' }, { name: 'status_code', type: 'number', description: 'HTTP 码' }],
  document: [{ name: 'path', type: 'string', description: '文件路径' }, { name: 'size', type: 'number', description: '文件大小' }],
  database: [{ name: 'items', type: 'array', description: 'SELECT 结果' }, { name: 'row_count', type: 'number', description: '行数' }, { name: 'affected_rows', type: 'number', description: '影响行数' }],
  scraper: [{ name: 'text', type: 'string', description: '纯文本' }, { name: 'data', type: 'any', description: 'JSON (json模式)' }, { name: 'length', type: 'number', description: '长度' }],
  loop: [{ name: 'items', type: 'array', description: '处理后列表' }, { name: 'count', type: 'number', description: '总数' }],
  delay: [{ name: 'delayed', type: 'number', description: '等待秒数' }, { name: 'resumed_at', type: 'number', description: '恢复时间戳' }],
  merge: [{ name: 'items', type: 'array', description: '合并列表 (append)' }, { name: 'merged', type: 'object', description: '合并对象 (combine)' }],
  transform: [{ name: 'items', type: 'array', description: '转换后列表' }, { name: 'count', type: 'number', description: '输出条数' }],
  approval: [{ name: 'approved', type: 'boolean', description: '是否通过' }, { name: 'approver', type: 'string', description: '审批人' }],
  subWorkflow: [{ name: 'execution_id', type: 'string', description: '执行 ID' }, { name: 'status', type: 'string', description: '状态' }, { name: 'variables', type: 'object', description: '输出变量' }],
  kvStore: [{ name: 'key', type: 'string', description: '键名' }, { name: 'value', type: 'any', description: '值 (get)' }, { name: 'exists', type: 'boolean', description: '是否存在' }],
}
